server:
    port: 8080
spring:
    datasource:
        tasks:
            jdbcUrl: jdbc:postgresql://localhost:5432/eisetasks
            username: anna
            password: anna
            driver-class-name: org.postgresql.Driver
jwt:
  issuer: 'annapeyl@gmail.com'
  signingKey: 'sZcps3y00xnFgpKs8rgoc6lri8uL4mqb1hJ'
  aTokenDuration: 30

configuration:
  meta:
    status: inbox
    order: desc
    start-page: 1
    page-size: 25
    min-page-size: 10
    max-page-size: 50