server:
    port: 8080
spring:
    datasource:
        tasks:
            jdbcUrl: jdbc:postgresql://localhost:5432/eisetasks
            username: anna
            password: anna
            driver-class-name: org.postgresql.Driver